<a href="https://colab.research.google.com/github/cristiandarioortegayubro/pandito/blob/main/colab/01_python_002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 p align="center">
<b>
<font color="DeepPink">
Saliendo de lo pandito
</font>
</h1>

<p align="center">
<img src="https://github.com/cristiandarioortegayubro/BDS/blob/main/images/Logo%20BDS%20Horizontal%208.png?raw=true" width="400">
</p>

<p align="center">
<img src="https://github.com/cristiandarioortegayubro/pandito/blob/main/images/imagen-001.png?raw=true" width="300">
</p>



 # **<font color="DeepPink">Python - Estructuras de datos</font>**

<p align="justify">
En este colab, vamos a desarrollar las estructuras de datos de Python. Conocer estas estructuras, es fundamental para el desarrollo de los contenidos propuestos. Por ese motivo, vamos a explayarnos en las estructuras de datos y en métodos usuales.
</p>


<p>
<font color="DeepPink">

👀 Antes que nada, verificamos la versión de Python con la cual estamos trabajando...

</font>
</p>

In [ ]:
!python3 -V

Python 3.10.12


## **<font color="DeepPink">Listas: flexibilidad y versatilidad</font>**

<p align="justify">
Comenzamos con una de las estructuras de datos más versátiles de Python: las listas.
<br><br>
Una lista es una colección ordenada de elementos, que pueden ser de cualquier tipo de datos. Las listas nos permiten almacenar y acceder a múltiples valores en una sola variable.


In [ ]:
precios_acciones = [150.75, 155.20, 160.50, 156.80, 162.30]
print(precios_acciones)

[150.75, 155.2, 160.5, 156.8, 162.3]


<p align="justify">
En este fragmento de código se define una lista llamada <code>precios_acciones</code> que contiene una serie de precios de acciones. Luego, se imprime la lista completa de precios de acciones.
<br><br>
A continuación, explicamos cómo funciona este código:

```python
precios_acciones = [150.75, 155.20, 160.50, 156.80, 162.30]
```

<p align="justify">
En esta línea, se define una lista llamada <code>precios_acciones</code>. La lista contiene varios valores numéricos que representan los precios de acciones en diferentes momentos o períodos. Cada valor en la lista corresponde a un precio de acción específico.

```python
print(precios_acciones)
```

<p align="justify">
Esta línea utiliza la función <code>print</code> para mostrar la lista <code>precios_acciones</code> en la consola. Al ejecutar esta línea, verás que se imprime la lista completa de precios de acciones tal como se definió anteriormente.
<br><br>
Por ejemplo, si se ejecuta este código, se obtiene la siguiente salida:

```
[150.75, 155.20, 160.50, 156.80, 162.30]
```

<p align="justify">
Este tipo de estructura de datos, una lista en este caso, es útil para almacenar y manipular colecciones de valores relacionados, como precios de acciones en este ejemplo. Puedes acceder a los elementos individuales de la lista, realizar cálculos y análisis, y realizar operaciones en conjunto utilizando métodos y funciones disponibles para trabajar con listas.

<p align="justify">
👀 A continuación, se desarrollan algunos métodos de las listas, acompañados de ejemplos relacionados con finanzas:

### **<font color="DeepPink">Método <code>append()</code></font>**


1. **`append()`**: Agrega un elemento al final de la lista.
   Ejemplo en finanzas: Registrar precios diarios de una acción a lo largo del tiempo.
   ```python
   precios_accion = [150.75, 155.20, 160.50]

   precios_accion.append(162.30)
   precios_accion
   ```



In [1]:
precios_accion = [150.75, 155.20, 160.50]

precios_accion.append(162.30)
precios_accion

[150.75, 155.2, 160.5, 162.3]

### **<font color="DeepPink">Método <code>extend()</code></font>**

2. **`extend()`**: Agrega múltiples elementos al final de la lista.
   Ejemplo en finanzas: Agregar nuevos activos a una cartera existente.
   ```python
   cartera_activos = ['AAPL', 'GOOG']
   nuevos_activos = ['AMZN', 'TSLA']

   cartera_activos.extend(nuevos_activos)
   cartera_activos
   ```



In [2]:
cartera_activos = ['AAPL', 'GOOG']
nuevos_activos = ['AMZN', 'TSLA']

cartera_activos.extend(nuevos_activos)
cartera_activos

['AAPL', 'GOOG', 'AMZN', 'TSLA']

### **<font color="DeepPink">Método <code>insert()</code></font>**

3. **`insert()`**: Inserta un elemento en una posición específica de la lista.
   Ejemplo en finanzas: Insertar un nuevo activo en una posición estratégica en una cartera.
   ```python
   cartera_activos.insert(2, 'MSFT')
   cartera_activos
   ```



In [3]:
cartera_activos.insert(2, 'MSFT')
cartera_activos

['AAPL', 'GOOG', 'MSFT', 'AMZN', 'TSLA']

### **<font color="DeepPink">Método <code>remove()</code></font>**

4. **`remove()`**: Elimina el primer elemento con un valor específico de la lista.
   Ejemplo en finanzas: Eliminar un activo de una cartera debido a un cambio de estrategia.
   ```python
   cartera_activos.remove('GOOG')
   cartera_activos
   ```



In [4]:
cartera_activos.remove('GOOG')
cartera_activos

['AAPL', 'MSFT', 'AMZN', 'TSLA']

### **<font color="DeepPink">Método <code>pop()</code></font>**

5. **`pop()`**: Elimina y devuelve el elemento en una posición específica de la lista.
   Ejemplo en finanzas: Vender un activo específico en una cartera.
   ```python
   activo_vendido = cartera_activos.pop(1)
   activo_vendido
   ```



In [5]:
activo_vendido = cartera_activos.pop(1)
activo_vendido

'MSFT'

## **<font color="DeepPink">Tuplas: inmutabilidad y seguridad</font>**

<p align="justify">
Las tuplas son similares a las listas, pero con una diferencia fundamental: son inmutables, lo que significa que no se pueden modificar después de la creación.
<br><br>
Las tuplas son ideales para almacenar datos que no deben cambiar, como fechas o coordenadas.


In [ ]:
fechas_inversion = ('2023-08-01', '2023-08-07', '2023-08-14')
print(fechas_inversion)

('2023-08-01', '2023-08-07', '2023-08-14')


### **<font color="DeepPink">Empaquetado</font>**

<p align="justify">
Ahora vamos a empaquetar y desempaquetar una tupla...
</p>


In [26]:
precios = 340.4 , 342.8 , 343.9, 342.5, 341.7, 342.1, 343.9
precios

(340.4, 342.8, 343.9, 342.5, 341.7, 342.1, 343.9)

### **<font color="DeepPink">Desempaquetado</font>**


In [27]:
dia01, dia02, dia03, dia04, dia05, dia06, dia07 = precios

In [28]:
print(f"Precios en la semana \n primer dia  $ {dia01:.2f} \n segundo dia $ {dia02:.2f}")

Precios en la semana 
 primer dia  $ 340.40 
 segundo dia $ 342.80


## **<font color="DeepPink">Diccionarios: asociación de Claves y Valores</font>**

<p align="justify">
Los diccionarios son estructuras que permiten almacenar datos en pares clave-valor. Son ideales para representar datos estructurados y asociativos, como información de empresas y sus respectivos precios.

In [ ]:
empresa_precios = {
    'Acme Inc.': 150.75,
    'XYZ Corp.': 155.20,
    'ABC Ltd.': 160.50}

print(empresa_precios)

{'Acme Inc.': 150.75, 'XYZ Corp.': 155.2, 'ABC Ltd.': 160.5}


<p align="justify">
Este fragmento de código crea un diccionario llamado <code>empresa_precios</code> que relaciona el nombre de una empresa con su respectivo precio.
<br><br>
Luego, imprime este diccionario completo. A continuación, te explico cómo funciona este código:

```python
empresa_precios = {
    'Acme Inc.': 150.75,
    'XYZ Corp.': 155.20,
    'ABC Ltd.': 160.50}
```

<p align="justify">
En estas líneas, se crea un diccionario llamado <code>empresa_precios</code>. Cada elemento del diccionario consiste en una clave (nombre de la empresa) y un valor (precio de la acción de la empresa). Los elementos están separados por comas y se encuentran dentro de llaves <code>{ }</code>.

- `'Acme Inc.'`, `'XYZ Corp.'` y `'ABC Ltd.'` son claves (o keys) que representan los nombres de las empresas.
- `150.75`, `155.20` y `160.50` son valores correspondientes a los precios de las acciones de las respectivas empresas.

<p align="justify">
Los diccionarios son estructuras de datos en Python que permiten almacenar pares clave-valor. Cada clave es única y se utiliza para acceder al valor asociado. En este caso, las claves son los nombres de las empresas y los valores son los precios de las acciones.

```python
print(empresa_precios)
```

<p align="justify">
Esta línea utiliza la función <code>print</code> para mostrar el diccionario <code>empresa_precios</code> en la consola. Al ejecutar este código, verás que se imprime el diccionario completo tal como se definió anteriormente.
<br><br>
Por ejemplo, si ejecutas el código, obtendrás la siguiente salida:

```
{'Acme Inc.': 150.75, 'XYZ Corp.': 155.20, 'ABC Ltd.': 160.50}
```



<p align="justify">
👀 A continuación, se desarrollan algunos métodos de los diccionarios, acompañados de ejemplos relacionados con finanzas:

### **<font color="DeepPink">Método <code>get()</code></font>**


1. **dict.get(clave, valor_predeterminado)**: Devuelve el valor asociado con una clave dada. Si la clave no existe, devuelve un valor predeterminado.

```python
cotizaciones = {'AAPL': 150.25, 'GOOG': 2500.60, 'AMZN': 3500.20}

precio_aapl = cotizaciones.get('AAPL', 0)  # Obtener el precio de AAPL, o 0 si no existe
print(f"Precio de AAPL: ${precio_aapl:.2f}")
```


In [7]:
cotizaciones = {'AAPL': 150.25, 'GOOG': 2500.60, 'AMZN': 3500.20}

precio_aapl = cotizaciones.get('AAPL', 0)  # Obtener el precio de AAPL, o 0 si no existe
print(f"Precio de AAPL: $ {precio_aapl:.2f}")

Precio de AAPL: $ 150.25


### **<font color="DeepPink">Método <code>keys()</code></font>**


2. **dict.keys()**: Devuelve una lista de todas las claves en el diccionario.

```python
cotizaciones = {'AAPL': 150.25, 'GOOG': 2500.60, 'AMZN': 3500.20}

activos = cotizaciones.keys()
print(f"Activos en cartera: {', '.join(activos)}")
```



In [8]:
cotizaciones = {'AAPL': 150.25, 'GOOG': 2500.60, 'AMZN': 3500.20}

activos = cotizaciones.keys()
print(f"Activos en cartera: {', '.join(activos)}")

Activos en cartera: AAPL, GOOG, AMZN


### **<font color="DeepPink">Método <code>values()</code></font>**

3. **dict.values()**: Devuelve una lista de todos los valores en el diccionario.

```python
cotizaciones = {'AAPL': 150.25, 'GOOG': 2500.60, 'AMZN': 3500.20}

precios = cotizaciones.values()
print(f"Precios en cartera: {', '.join(map(str, precios))}")
```



In [9]:
cotizaciones = {'AAPL': 150.25, 'GOOG': 2500.60, 'AMZN': 3500.20}

precios = cotizaciones.values()
print(f"Precios en cartera: {', '.join(map(str, precios))}")

Precios en cartera: 150.25, 2500.6, 3500.2


### **<font color="DeepPink">Método <code>items()</code></font>**

4. **dict.items()**: Devuelve una lista de tuplas (clave, valor) para cada par en el diccionario.

```python
cotizaciones = {'AAPL': 150.25, 'GOOG': 2500.60, 'AMZN': 3500.20}

items = cotizaciones.items()
print(f"Items: {', '.join(map(str, items))}")
```



In [14]:
cotizaciones = {'AAPL': 150.25, 'GOOG': 2500.60, 'AMZN': 3500.20}

items = cotizaciones.items()
print(f"Items: {', '.join(map(str, items))}")

Items: ('AAPL', 150.25), ('GOOG', 2500.6), ('AMZN', 3500.2)


### **<font color="DeepPink">Método <code>pop()</code></font>**

5. **dict.pop(clave, valor_predeterminado)**: Elimina la clave y devuelve su valor. Si la clave no existe, devuelve un valor predeterminado.

```python
cotizaciones = {'AAPL': 150.25, 'GOOG': 2500.60, 'AMZN': 3500.20}

precio_amzn = cotizaciones.pop('AMZN', 0)  # Eliminar AMZN y obtener su precio, o 0 si no existe
print(f"Precio eliminado de AMZN: ${precio_amzn:.2f}")
```


In [16]:
cotizaciones = {'AAPL': 150.25, 'GOOG': 2500.60, 'AMZN': 3500.20}

precio_amzn = cotizaciones.pop('AMZN', 0)
print(f"Precio eliminado de AMZN: $ {precio_amzn:.2f}")

Precio eliminado de AMZN: $ 3500.20


### **<font color="DeepPink">Método <code>update()</code></font>**


6. **dict.update(otro_diccionario)**: Fusiona otro diccionario en el diccionario actual.

```python
cotizaciones = {'AAPL': 150.25, 'GOOG': 2500.60}
cotizaciones_nuevas = {'AMZN': 3500.20, 'MSFT': 300.50}

cotizaciones.update(cotizaciones_nuevas)
print(f"Cotizaciones actualizadas: {cotizaciones}")
```

In [17]:
cotizaciones = {'AAPL': 150.25, 'GOOG': 2500.60}
cotizaciones_nuevas = {'AMZN': 3500.20, 'MSFT': 300.50}

cotizaciones.update(cotizaciones_nuevas)
print(f"Cotizaciones actualizadas: {cotizaciones}")

Cotizaciones actualizadas: {'AAPL': 150.25, 'GOOG': 2500.6, 'AMZN': 3500.2, 'MSFT': 300.5}


## **<font color="DeepPink">Conjuntos: almacenamiento de elementos únicos</font>**

<p align="justify">
Los conjuntos son colecciones de elementos únicos y desordenados. Son ideales para eliminar duplicados y verificar la pertenencia de elementos en un conjunto de datos.


In [ ]:
sectores_empresariales = {'Tecnología', 'Finanzas', 'Energía'}
print(sectores_empresariales)

{'Finanzas', 'Energía', 'Tecnología'}


### **<font color="DeepPink">Método <code>add()</code></font>**


1. **add(elemento)**: Agrega un elemento al conjunto si no está presente.

   Ejemplo en finanzas:
   ```python
   activos = {'AAPL', 'GOOG', 'AMZN'}

   activos.add('TSLA')
   activos
   ```



In [18]:
activos = {'AAPL', 'GOOG', 'AMZN'}

activos.add('TSLA')
activos

{'AAPL', 'AMZN', 'GOOG', 'TSLA'}

### **<font color="DeepPink">Método <code>remove()</code></font>**

2. **remove(elemento)**: Elimina un elemento del conjunto si está presente, de lo contrario, genera un error.

   Ejemplo en finanzas:
   ```python
   activos = {'AAPL', 'GOOG', 'AMZN'}

   activos.remove('GOOG')
   activos
   ```



In [19]:
activos = {'AAPL', 'GOOG', 'AMZN'}

activos.remove('GOOG')
activos

{'AAPL', 'AMZN'}

### **<font color="DeepPink">Método <code>discard()</code></font>**

3. **discard(elemento)**: Elimina un elemento del conjunto si está presente, pero no genera un error si no se encuentra.

   Ejemplo en finanzas:
   ```python
   activos = {'AAPL', 'GOOG', 'AMZN'}

   activos.discard('TSLA')
   activos
   ```




In [20]:
activos = {'AAPL', 'GOOG', 'AMZN'}

activos.discard('TSLA')
activos

{'AAPL', 'AMZN', 'GOOG'}

### **<font color="DeepPink">Método <code>union()</code></font>**

4. **union(otro_conjunto)**: Retorna un nuevo conjunto con todos los elementos únicos de ambos conjuntos.

   Ejemplo en finanzas:
   ```python
   activos1 = {'AAPL', 'GOOG', 'AMZN'}
   activos2 = {'GOOG', 'TSLA', 'NFLX'}

   activos_totales = activos1.union(activos2)
   activos_totales
   ```



In [21]:
activos1 = {'AAPL', 'GOOG', 'AMZN'}
activos2 = {'GOOG', 'TSLA', 'NFLX'}

activos_totales = activos1.union(activos2)
activos_totales

{'AAPL', 'AMZN', 'GOOG', 'NFLX', 'TSLA'}

### **<font color="DeepPink">Método <code>intersection()</code></font>**

5. **intersection(otro_conjunto)**: Retorna un nuevo conjunto con los elementos comunes entre ambos conjuntos.

   Ejemplo en finanzas:
   ```python
   cartera1 = {'AAPL', 'GOOG', 'AMZN'}
   cartera2 = {'GOOG', 'TSLA', 'NFLX'}

   activos_comunes = cartera1.intersection(cartera2)
   activos_comunes
   ```



In [22]:
cartera1 = {'AAPL', 'GOOG', 'AMZN'}
cartera2 = {'GOOG', 'TSLA', 'NFLX'}

activos_comunes = cartera1.intersection(cartera2)
activos_comunes

{'GOOG'}

### **<font color="DeepPink">Método <code>difference()</code></font>**

6. **difference(otro_conjunto)**: Retorna un nuevo conjunto con los elementos que están en el conjunto original pero no en el otro conjunto.

   Ejemplo en finanzas:
   ```python
   activos_portafolio = {'AAPL', 'GOOG', 'AMZN', 'TSLA'}
   activos_excluidos = {'AAPL', 'TSLA'}

   activos_restantes = activos_portafolio.difference(activos_excluidos)
   activos_restantes
   ```



In [23]:
activos_portafolio = {'AAPL', 'GOOG', 'AMZN', 'TSLA'}
activos_excluidos = {'AAPL', 'TSLA'}

activos_restantes = activos_portafolio.difference(activos_excluidos)
activos_restantes

{'AMZN', 'GOOG'}

### **<font color="DeepPink">Método <code>issubset()</code></font>**

7. **issubset(otro_conjunto)**: Verifica si el conjunto es un subconjunto del otro conjunto.

   Ejemplo en finanzas:
   ```python
   activos_portafolio = {'AAPL', 'GOOG', 'AMZN', 'TSLA'}
   activos_favoritos = {'AAPL', 'GOOG'}

   es_subconjunto = activos_favoritos.issubset(activos_portafolio)
   es_subconjunto
   ```



In [24]:
activos_portafolio = {'AAPL', 'GOOG', 'AMZN', 'TSLA'}
activos_favoritos = {'AAPL', 'GOOG'}

es_subconjunto = activos_favoritos.issubset(activos_portafolio)
es_subconjunto

True

### **<font color="DeepPink">Método <code>issuperset()</code></font>**

8. **issuperset(otro_conjunto)**: Verifica si el conjunto es un superconjunto del otro conjunto.

   Ejemplo en finanzas:
   ```python
   activos_portafolio = {'AAPL', 'GOOG', 'AMZN', 'TSLA'}
   activos_favoritos = {'AAPL', 'GOOG'}

   es_superconjunto = activos_portafolio.issuperset(activos_favoritos)
   es_superconjunto
   ```

In [25]:
activos_portafolio = {'AAPL', 'GOOG', 'AMZN', 'TSLA'}
activos_favoritos = {'AAPL', 'GOOG'}

es_superconjunto = activos_portafolio.issuperset(activos_favoritos)
es_superconjunto

True

## **<font color="DeepPink">Indexación y selección de datos</font>**

<p align="justify">
A través de la indexación, podemos acceder y manipular datos en estas estructuras.
<br><br>
Desde la selección de elementos individuales hasta la aplicación de operaciones en lotes, las capacidades de indexación de Python permiten a los analistas extraer información relevante y realizar cálculos significativos.


In [ ]:
# Acceso a elementos en una lista
primer_precio = precios_acciones[0]

In [ ]:
primer_precio

150.75

In [ ]:
# Acceso a valores de un diccionario
precio_acme = empresa_precios['Acme Inc.']

In [ ]:
precio_acme

150.75

 # **<font color="DeepPink">Conclusiones</font>**

<p align="justify">
👀 En este colab nosotros:
<br><br>
✅ Definimos Estructuras de datos.
<br>
✅ Vemos las Listas.
<br>
✅ Vemos las Tuplas.
<br>
✅ Vemos los Diccionarios.
<br>
✅ Vemos los Conjuntos.
<br>
✅ Indexamos y seleccionamos datos.
<br>
<br>
<p align="center">
<img src="https://www.python.org/static/community_logos/python-powered-h-70x91.png">
</p>

---